version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Mapeando a porta 5433 do host para a 5432 do container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: